[tool.poetry]
name = "statistics-example"
version = "0.1.0"
description = ""
authors = ["chenhh <chenhh@eva01>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipython = "^8.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
